import { useState } from 'react';
import { Brain, Check, Edit3, RefreshCw, Sparkles, Clock, User } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { STRParagraph } from '@/types/str';
import { format } from 'date-fns';

interface STRParagraphBlockProps {
  paragraph: STRParagraph;
  isGenerating?: boolean;
  onGenerate: () => void;
  onRegenerate: () => void;
  onEdit: (content: string) => void;
  onAccept: () => void;
  readOnly?: boolean;
}

export function STRParagraphBlock({
  paragraph,
  isGenerating = false,
  onGenerate,
  onRegenerate,
  onEdit,
  onAccept,
  readOnly = false,
}: STRParagraphBlockProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(paragraph.content);

  const handleSaveEdit = () => {
    onEdit(editedContent);
    setIsEditing(false);
  };

  const handleCancelEdit = () => {
    setEditedContent(paragraph.content);
    setIsEditing(false);
  };

  // Empty paragraph - show generate action
  if (!paragraph.content && !isGenerating) {
    return (
      <div className="rounded-lg border-2 border-dashed border-muted-foreground/25 p-6 text-center">
        <div className="flex flex-col items-center gap-3">
          <div className="rounded-full bg-primary/10 p-3">
            <Sparkles className="h-5 w-5 text-primary" />
          </div>
          <div>
            <p className="text-sm text-muted-foreground mb-2">
              No content yet. Generate a narrative paragraph using FinCrisS Agent.
            </p>
            <Button
              variant="outline"
              size="sm"
              onClick={onGenerate}
              disabled={readOnly}
              className="gap-2"
            >
              <Brain className="h-4 w-4" />
              Generate with FinCrisS Agent
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // Generating state
  if (isGenerating) {
    return (
      <div className="rounded-lg border border-primary/30 bg-primary/5 p-6">
        <div className="flex items-center gap-3">
          <div className="animate-spin rounded-full bg-primary/20 p-2">
            <Brain className="h-4 w-4 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium text-primary">FinCrisS Agent is generating...</p>
            <p className="text-xs text-muted-foreground">
              Analyzing case data, transactions, and risk indicators
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Content exists
  const showAiHighlight = paragraph.isAiGenerated && !paragraph.isEdited;

  return (
    <div
      className={cn(
        'rounded-lg border p-4 transition-all',
        showAiHighlight
          ? 'border-primary/30 bg-primary/5'
          : 'border-border bg-background'
      )}
    >
      {/* Header with metadata */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          {showAiHighlight && (
            <Badge variant="outline" className="text-primary border-primary text-xs gap-1">
              <Brain className="h-3 w-3" />
              Draft generated by FinCrisS Agent
            </Badge>
          )}
          {paragraph.isEdited && (
            <Badge variant="outline" className="text-muted-foreground text-xs gap-1">
              <User className="h-3 w-3" />
              Investigator edited
            </Badge>
          )}
        </div>
        {!readOnly && !isEditing && (
          <div className="flex items-center gap-1">
            {showAiHighlight && (
              <Button variant="ghost" size="sm" onClick={onAccept} className="text-xs gap-1">
                <Check className="h-3 w-3" />
                Accept
              </Button>
            )}
            <Button variant="ghost" size="sm" onClick={onRegenerate} className="text-xs gap-1">
              <RefreshCw className="h-3 w-3" />
              Regenerate
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setIsEditing(true)}
              className="text-xs gap-1"
            >
              <Edit3 className="h-3 w-3" />
              Edit
            </Button>
          </div>
        )}
      </div>

      {/* Content */}
      {isEditing ? (
        <div className="space-y-3">
          <Textarea
            value={editedContent}
            onChange={(e) => setEditedContent(e.target.value)}
            className="min-h-[120px] text-sm"
            placeholder="Enter narrative content..."
          />
          <div className="flex items-center justify-end gap-2">
            <Button variant="ghost" size="sm" onClick={handleCancelEdit}>
              Cancel
            </Button>
            <Button size="sm" onClick={handleSaveEdit}>
              <Check className="mr-1 h-3 w-3" />
              Save Changes
            </Button>
          </div>
        </div>
      ) : (
        <p className="text-sm leading-relaxed whitespace-pre-wrap">{paragraph.content}</p>
      )}

      {/* Metadata footer */}
      {(paragraph.generatedAt || paragraph.editedAt) && (
        <div className="flex items-center gap-4 mt-3 pt-3 border-t border-border/50 text-xs text-muted-foreground">
          {paragraph.generatedAt && (
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              Generated: {format(paragraph.generatedAt, 'MMM dd, yyyy HH:mm')}
            </span>
          )}
          {paragraph.editedAt && paragraph.editedBy && (
            <span className="flex items-center gap-1">
              <Edit3 className="h-3 w-3" />
              Edited by {paragraph.editedBy}: {format(paragraph.editedAt, 'MMM dd, yyyy HH:mm')}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
