import { FileText, Printer } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { STRSection } from '@/types/str';

interface STRPreviewPanelProps {
  sections: STRSection[];
  caseId: string;
  customerName: string;
  investigatorComments?: string;
}

export function STRPreviewPanel({
  sections,
  caseId,
  customerName,
  investigatorComments,
}: STRPreviewPanelProps) {
  const sectionTitles: Record<string, string> = {
    grounds_of_suspicion: 'Grounds of Suspicion',
    transaction_narrative: 'Transaction Narrative',
    customer_background: 'Customer Background',
    supporting_indicators: 'Supporting Indicators',
  };

  const getSectionContent = (sectionType: string) => {
    const section = sections.find((s) => s.type === sectionType);
    if (!section) return null;
    const content = section.paragraphs
      .filter((p) => p.content)
      .map((p) => p.content)
      .join('\n\n');
    return content || null;
  };

  return (
    <Card className="h-full">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            <div>
              <CardTitle className="text-lg">STR Preview</CardTitle>
              <CardDescription>FIU / Regulatory Format</CardDescription>
            </div>
          </div>
          <Button variant="outline" size="sm" className="gap-2">
            <Printer className="h-4 w-4" />
            Print
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="rounded-lg border bg-card p-6 space-y-6 max-h-[600px] overflow-y-auto">
          {/* Header */}
          <div className="text-center border-b pb-4">
            <h2 className="text-lg font-bold uppercase tracking-wide">
              Suspicious Transaction Report
            </h2>
            <p className="text-sm text-muted-foreground mt-1">
              Case Reference: {caseId}
            </p>
            <p className="text-sm text-muted-foreground">
              Subject: {customerName}
            </p>
          </div>

          {/* Sections */}
          {['grounds_of_suspicion', 'transaction_narrative', 'customer_background', 'supporting_indicators'].map(
            (sectionType) => {
              const content = getSectionContent(sectionType);
              if (!content) return null;
              return (
                <div key={sectionType}>
                  <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground mb-2">
                    {sectionTitles[sectionType]}
                  </h3>
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{content}</p>
                </div>
              );
            }
          )}

          {/* Investigator Comments */}
          {investigatorComments && (
            <>
              <Separator />
              <div>
                <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground mb-2">
                  Investigator Remarks
                </h3>
                <p className="text-sm leading-relaxed whitespace-pre-wrap">
                  {investigatorComments}
                </p>
              </div>
            </>
          )}

          {/* Footer placeholder */}
          <Separator />
          <div className="text-center text-xs text-muted-foreground">
            <p>This document is confidential and intended for regulatory filing purposes only.</p>
            <p className="mt-1">Generated by FinCrisS AML Platform</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
