services:
  fincriss:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-https://api.fincriss.com}
    image: fincriss:latest
    container_name: fincriss
    restart: unless-stopped
    networks:
      - fincriss-bcknd_default

networks:
  fincriss-bcknd_default:
    external: true
